services:
  pomerium:
    image: pomerium/pomerium:v0.32.8
    ports:
      - '443:443'
    restart: always
    environment:
      POMERIUM_ZERO_TOKEN: ${POMERIUM_ZERO_TOKEN:?Set POMERIUM_ZERO_TOKEN in the environment}
      XDG_CACHE_HOME: /var/cache
    volumes:
      - pomerium-cache:/var/cache
    networks:
      main:
        aliases:
          - verify.first-gator-112.pomerium.app

  verify:
    image: pomerium/verify:latest
    restart: always
    networks:
      main:
        aliases:
          - verify

networks:
  main: {}

volumes:
  pomerium-cache: {}
